version: '3.5'

services:
  plarin-api:
    container_name: plarin-api
    build:
      context: .
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - ./volumes/logs:/app/logs

  mongodb:
    container_name: mongo
    image: mongo:5.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./volumes/mongo:/data/db
      - ./volumes/mongo/configdb:/data/configdb
